# Generated by Django 3.0.5 on 2020-11-26 21:51

from django.db import migrations, models
import django.db.models.deletion
import ebooks.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_auto_20201126_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txt_book', models.FileField(blank=True, null=True, upload_to=ebooks.models.ebook_directory_path)),
                ('pdf_book', models.FileField(blank=True, null=True, upload_to=ebooks.models.ebook_directory_path)),
                ('txt_download_count', models.IntegerField(default=0, editable=False)),
                ('pdf_download_count', models.IntegerField(default=0, editable=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
