# Generated by Django 3.0.5 on 2020-11-29 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ebooks.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txt_book', models.FileField(blank=True, null=True, upload_to=ebooks.models.ebook_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])])),
                ('pdf_book', models.FileField(blank=True, null=True, upload_to=ebooks.models.ebook_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('download_count', models.IntegerField(default=0, editable=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
