# Generated by Django 3.0.5 on 2020-11-26 18:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_opinion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('txt_book', models.FileField(blank=True, null=True, upload_to='ebooks/<django.db.models.query_utils.DeferredAttribute object at 0x00000182C1B02CD0>/')),
                ('pdf_book', models.FileField(blank=True, null=True, upload_to='ebooks/<django.db.models.query_utils.DeferredAttribute object at 0x00000182C1B02CD0>/')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
            ],
        ),
    ]
