# Generated by Django 3.0.5 on 2020-11-27 12:34

import django.core.validators
from django.db import migrations, models
import ebooks.models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='pdf_book',
            field=models.FileField(blank=True, null=True, upload_to=ebooks.models.ebook_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='txt_book',
            field=models.FileField(blank=True, null=True, upload_to=ebooks.models.ebook_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
