# Generated by Django 3.0.5 on 2021-01-18 00:53

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, default='Maintenance', help_text='Book availability', max_length=1, verbose_name=books.models.BookInstance.LoanStatus),
        ),
    ]
