# Generated by Django 3.0.5 on 2020-11-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_opinion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinion',
            options={'ordering': ['-date_posted']},
        ),
    ]
