# Generated by Django 3.0.5 on 2020-11-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201126_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='on_loan_duration',
            field=models.IntegerField(default=4, help_text='Months'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='on_loan_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
