# Generated by Django 3.0.5 on 2020-11-24 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201115_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
