# Generated by Django 3.0.5 on 2021-01-19 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_auto_20210118_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['created_date']},
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='on_loan_duration',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='on_loan_end',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='on_loan_start',
        ),
        migrations.CreateModel(
            name='BookReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(auto_now_add=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.BookInstance')),
                ('booker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reservation_date'],
            },
        ),
        migrations.CreateModel(
            name='BookRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_loan_start', models.DateField(blank=True, null=True)),
                ('on_loan_duration', models.IntegerField(default=4, help_text='Months')),
                ('on_loan_end', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.BookInstance')),
                ('booker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['on_loan_start'],
            },
        ),
    ]
