# Generated by Django 3.0.5 on 2020-11-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookinstance_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
    ]
