# Generated by Django 3.0.5 on 2020-11-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20201127_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='on_loan_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
