# Generated by Django 3.0.5 on 2020-11-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookinstance_on_loan_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='opinion',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
