# Generated by Django 3.0.5 on 2021-01-20 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_change_default_book_status_to_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrental',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookInstance', unique=True),
        ),
        migrations.AlterField(
            model_name='bookreservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookInstance', unique=True),
        ),
    ]
