# Generated by Django 3.0.5 on 2020-11-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_book',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite_genre',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_phone',
            field=models.CharField(default='', max_length=9),
        ),
    ]
