# Generated by Django 3.0.5 on 2020-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201126_2246'),
        ('users', '0002_auto_20201122_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='book_list',
            field=models.ManyToManyField(to='books.BookInstance'),
        ),
    ]
