# Generated by Django 3.0.5 on 2020-11-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201126_2246'),
        ('users', '0003_profile_book_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='book_list',
            field=models.ManyToManyField(blank=True, to='books.BookInstance'),
        ),
    ]
