# Generated by Django 3.0.5 on 2020-11-27 22:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookinstance_on_loan_end'),
        ('users', '0004_auto_20201127_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('day_exceeded', models.IntegerField()),
                ('value', models.FloatField()),
                ('book_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.BookInstance')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='payments',
            field=models.ManyToManyField(blank=True, to='users.Payments'),
        ),
    ]
