# Generated by Django 3.0.5 on 2020-11-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookinstance_on_loan_end'),
        ('users', '0005_auto_20201128_0032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
