# Generated by Django 3.0.5 on 2020-11-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201128_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='on_loan_end',
            field=models.DateField(null=True),
        ),
    ]
