# Generated by Django 3.0.5 on 2020-11-27 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_payment_on_loan_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='payments',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
